### ISSUE TITLE
.fetch() is firing twice, Is this normal when transforming the model inside a dataTransform function?

### ISSUE THREAD

**Issue by macCesar** [jasonkneen/mocx#1]
Hi Jason...

In the following project, I'm using the dataTransform function to calculate a balance of all the transactions in the Collection.

And I'm calling .fetch() once, but the dataTransform function is called twice.

But, if I remove:

```javascript
// model.trigger("change"); 
```

From mocx.js, inside the Backbone.sync function, the balance is calculated correctly.

Can I safely remove it without affecting anything else like .get(), .set(), .save() or sync() ?

Or what am I doing wrong?

Please advice... Thanks!!

**BTW: I'm only testing it on iOS, with SDK 7.1.1.GA and mocx.js inside /lib folder.**

alloy.js
```javascript
Alloy.Globals.mocx = require('mocx');

Alloy.Globals.mocx.createCollection('movimientos', [
  {
    ammount: 10,
    transaction: 'income',
    description: 'This is an Income'
  }, {
    ammount: 10,
    transaction: 'expense',
    description: 'Expense...'
  }, {
    ammount: 10,
    transaction: 'income',
    description: 'This is an Income'
  }, {
    ammount: 10,
    transaction: 'expense',
    description: 'Expense...'
  }, {
    ammount: 5,
    transaction: 'expense',
    description: 'Expense...'
  }, {
    ammount: 10,
    transaction: 'income',
    description: 'With this Icome the balance should be $5.00'
  }
]);
```

index.js
```javascript
var balance = 0;
var utilities = require('utilities');

(function constructor() {
  Alloy.Collections.movimientos.fetch();
	
  $.balance.setText('Balance: ' + utilities.withCurrency.format(balance));

  $.index.open();
}());


function transformModel(model) {
  var model = model.toJSON();

  if (model.transaction === 'income') {
    balance += model.ammount;
    model.ammount = utilities.withCurrency.format(model.ammount);
  } else {
    model.rojo = '#F00';
    balance -= model.ammount;
    model.ammount = '-' + utilities.withCurrency.format(model.ammount);
  }

  // console.log is showing 12 times, instead of 6 (The amount of transactions in the collection)
  console.log('Balance...', balance);

  return model;
}
```

index.xml
```xml
<Alloy>
  <Window>
    <TableView dataCollection="movimientos" dataTransform="transformModel">
      <TableViewRow>
        <View>
          <Label id="ammount" text="{ammount}" color="{rojo}"/>
          <Label id="description" text="{description}"/>
        </View>
      </TableViewRow>
    </TableView>
		
    <Label id="balance" />
  </Window>
</Alloy>
```

lib/utilities.js
```javascript
// Create our number formatter.
var withCurrency = new Intl.NumberFormat('es-MX', {
  currency: 'MXN',
  style: 'currency',
  minimumFractionDigits: 2
});
exports.withCurrency = withCurrency;
```

index.tss
```css
'Window': {
  backgroundColor: '#FFF'
}

'TableView': {
  top: 0,
  bottom: 50
}

'TableViewRow': {
  height: 50
}

'View': {
  left: 0,
  layout: 'vertical'
}

'Label': {
  left: 20,
  width: Ti.UI.FILL,
  textAlign: Ti.UI.TEXT_ALIGNMENT_LEFT
}

'#description': {
  color: 'gray',
  font: { fontSize: 14 }
}

'#balance': {
  left: 0,
  bottom: 0,
  height: 50,
  color: '#FFF',
  font: { fontSize: 22 },
  backgroundColor: '#002550',
  textAlign: Ti.UI.TEXT_ALIGNMENT_CENTER
}
```

Wrong Balance:
<img width="544" alt="wrong balance" src="https://user-images.githubusercontent.com/1383124/39658402-7a2aaf66-4fd9-11e8-943b-06b61351838a.png">

Console Log:
<img width="381" alt="console log" src="https://user-images.githubusercontent.com/1383124/39658522-186c36f8-4fdb-11e8-9fb0-334dff27fe78.png">

After removing model.trigger('change');

Correct Balance:
<img width="544" alt="correct balance by removing model trigger change" src="https://user-images.githubusercontent.com/1383124/39658403-800db130-4fd9-11e8-827d-76445288b116.png">

Console Log:
<img width="345" alt="without model trigger chage" src="https://user-images.githubusercontent.com/1383124/39658811-aa223a3e-4fe0-11e8-9167-001381154c8c.png">
